web/app/main/forms.py
from wtforms import BooleanField, DateTimeField, IntegerField, StringField, SubmitField, PasswordField
from wtforms.validators import Email, Length, Required
from  ..models import User
from flask_wtf import FlaskForm
from wtforms import ValidationError


class SignupForm(FlaskForm):
    submit = SubmitField('Anmäl mig')


class ProfileForm(FlaskForm):
    email = StringField('Email', validators=[Required(),
                                             Length(0, 254),
                                             Email()])
    first_name = StringField('Förnamn', validators=[Length(0, 64)])
    last_name = StringField('Efternamn', validators=[Length(0, 64)])
    phone = StringField('Telefonnummer', validators=[Length(0, 32)])
    submit = SubmitField('Spara')


class BankAccountForm(FlaskForm):
    bank = StringField('Bank', validators=[Required(), Length(0, 64)])
    clearing = StringField('Clearingnummer', validators=[Length(0, 16)])
    number = StringField('Kontonummer', validators=[Length(0, 64)])
    submit = SubmitField('Spara')


class VolunteerForm(FlaskForm):
    available_week_before = BooleanField('En vecka innan')
    available_thursday = BooleanField('Torsdag')
    available_friday = BooleanField('Fredag')
    available_saturday_part_a = BooleanField('Lördag förmiddag')
    available_saturday_part_b = BooleanField('Lördag eftermiddag')
    available_sunday = BooleanField('Söndag')
    submit = SubmitField('Anmäl')


class EventForm(FlaskForm):
    start = DateTimeField('Start')
    end = DateTimeField('Slut')
    signup_start = DateTimeField('Anmälan öppnar')
    signup_end = DateTimeField('Anmälan stänger')
    limit = IntegerField('Max antal deltagare')
    submit = SubmitField('Skapa nytt')

web/app/main/__init__.py
from flask import Blueprint

# Initialization of main blueprint.
main = Blueprint('main', __name__)

from . import views, errors

web/app/main/views.py
from flask import abort, current_app, flash, redirect, render_template, url_for, jsonify
from flask_login import fresh_login_required, login_required, current_user, login_user
from . import main
from .forms import EventForm, SignupForm, ProfileForm, BankAccountForm, VolunteerForm
from .. import db
from ..models import get_current_event, User, Attendance, BankAccount, Event
from ..decorators import admin_required, check_confirmed
from ..email import send_email
from datetime import datetime

@main.route('/', methods=['GET', 'POST'])
def index():
    current_event = get_current_event()

    form = SignupForm()
    if form.validate_on_submit():
        current_event = Event.query.filter(Event.start > datetime.utcnow()).order_by(Event.start).with_for_update().first()

        if current_event.signup_open() and not current_user.is_anonymous:
            current_app.logger.info('Signing up user {}.'.format(current_user.email))
            attendance = Attendance()
            attendance.event = current_event
            attendance.user = current_user

            attendance.seller_id = Event.generate_seller_id(current_event.next_seller_id)
            current_event.next_seller_id = current_event.next_seller_id + 1

            db.session.add(attendance)
            db.session.commit()
            send_email.delay(current_user.email, 'Välkommen som säljare', 'main/email/seller', seller_id=attendance.seller_id)
            flash('Grattis! Du är nu anmäld. Ett mail har skickats till din epostadress med instruktioner.')
        else:
            flash('Anmälan kunde inte göras.')

    if not current_user.is_anonymous:
        attending = current_event in [attendance.event for attendance in current_user.events]
    else:
        attending = None

    return render_template('main/index.html', form=form,
                                              current_event=current_event,
                                              attending=attending)


@main.route('/profile', methods=['GET', 'POST'])
@login_required
@check_confirmed
def profile():
    user = current_user
    form = ProfileForm(email=user.email,
                       first_name=user.first_name,
                       last_name=user.last_name,
                       phone=user.phone)
    if form.validate_on_submit():
        user.first_name = form.first_name.data
        user.last_name = form.last_name.data
        user.phone = form.phone.data
        db.session.commit()
        flash('Din profil har uppdaterats.')
        return redirect(url_for('main.index'))
    return render_template('main/profile.html', form=form, user=user)


@main.route('/profile/bank', methods=['GET', 'POST'])
@login_required
@check_confirmed
def profile_bank():
    form = BankAccountForm()
    if form.validate_on_submit():
        user = current_user
        account = BankAccount(bank = form.bank.data,
                              clearing = ''.join(i for i in form.clearing.data if i.isdigit),
                              number = ''.join(i for i in form.number.data if i.isdigit))
        user.account = account
        db.session.add(account)
        db.session.commit()
        flash('Dina kontouppgifter har uppdaterats.')
        return redirect(url_for('main.profile'))
    return render_template('main/profile_bank.html', form=form)


@main.route('/personal')
def personal():
    return render_template('main/personal.html')

@main.route('/dashboard')
@admin_required
def dashboard():
    current_event = get_current_event()
    users = User.query.all()
    events = Event.query.all()
    unconfirmed_email_users = User.query.filter_by(confirmed = False).all()
    from random import randint
    return render_template('main/dashboard.html', users=users, events=events,
                                                  unconfirmed_email_users=unconfirmed_email_users,
                                                  current_event=current_event)

@main.route('/stats/event')
@admin_required
def event_stats():
    event = get_current_event()
    data = {
        'max_attendees': event.limit,
        'attendees': len(event.attendees),
        'free': event.limit - len(event.attendees)
    }
    return jsonify(data)


@main.route('/stats/users')
@admin_required
def users_stats():
    total_count = User.query.filter_by().count()
    confirmed_count = User.query.filter_by(confirmed=True).count()
    data = {
        'total_count': total_count,
        'confirmed_count': confirmed_count,
        'unconfirmed_count': total_count - confirmed_count
    }
    return jsonify(data)


@main.route('/user/<int:id>')
@admin_required
def user_profile(id):
    user = User.query.get(id)
    return render_template('main/user_profile.html', user=user)


@main.route('/info')
def info():
    return render_template('main/info.html')


@main.route('/volunteer')
def volunteer():
    form = VolunteerForm()
    if form.validate_on_submit():
        pass

    current_event = get_current_event()
    return render_template('main/volunteer.html', current_event=current_event, form=form)


@main.route('/user')
@admin_required
def list_users():
    users = db.session.query(User).order_by(User.last_name, User.first_name).all()
    return render_template('main/list_users.html', users=users)


@main.route('/event', methods=['GET', 'POST'])
@admin_required
def list_events():
    form = EventForm()
    if form.validate_on_submit():
        pass

    events = db.session.query(Event).order_by(Event.start.desc()).all()
    return render_template('main/list_events.html', form=form, events=events)


@main.route('/event/<int:id>', methods=['GET', 'POST'])
@admin_required
def event(id):
    event = Event.query.get(id)
    return render_template('main/event.html', event=event)


@main.route('/event/<int:id>/with_bank')
#@fresh_login_required
@admin_required
def event_with_bank_details(id):
    event = Event.query.get(id)
    return render_template('main/event_with_bank_details.html', event=event)


@main.route('/gdpr')
def gdpr():
    return render_template('main/gdpr.html')

web/app/templates/main/dashboard.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
  <div class="row">
    <div class="col-md-12">
      <h1>Admin</h1>
      <hr>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <h3>Administrera</h3>
      <p><a href="{{ url_for('main.list_users') }}">Administrera användare</a></p>
      <p><a href="{{ url_for('main.list_events') }}">Administrera event</a></p>
    </div>
    <div class="col-md-4">
      <h3>Anmälda till aktuellt event</h3>
      <canvas id="event-stats"></canvas>
    </div>
    <div class="col-md-4">
      <h3>Status för alla användare</h3>
      <canvas id="user-stats"></canvas>
    </div>
  </div>
{% endblock %}

{% block scripts %}
  {{ super() }}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.min.js"></script>
  <script type="text/javascript">
    var ctx = document.getElementById("event-stats");
    var eventStatsChart = new Chart(ctx, {
      type: 'doughnut',
      data: {
        labels: ["Anmälda", "Lediga platser"],
        datasets: [{
          label: '# of votes',
          data: [],
          backgroundColor: [
            'rgba(121, 62, 135, 1)',
            'rgba(86, 192, 215, 1)'
          ]
        }]},
      options: {
        legend: {
          display: true,
          position: 'right'
        }
      }
    });

    var request = new XMLHttpRequest();
    request.open('GET', '/stats/event', true);

    request.onload = function() {
      if (request.status >= 200 && request.status < 400) {
        var data = JSON.parse(request.responseText);
        eventStatsChart.config.data.datasets[0].data = [data.attendees, data.free];
        eventStatsChart.update();
      } else {
        console.log('There was an issue on the server.');
      }
    };

    request.onerror = function() {
      console.log('There was an issue with the request.');
    };

    request.send();
  </script>
  <script type="text/javascript">
    var ctx = document.getElementById("user-stats");
    var usersChart = new Chart(ctx, {
      type: 'doughnut',
      data: {
        labels: ["Bekräftade", "Obekräftade"],
        datasets: [{
          label: '# of votes',
          data: [],
          backgroundColor: [
            'rgba(121, 62, 135, 1)',
            'rgba(86, 192, 215, 1)',
            'rgba(252, 198, 73, 1)'
          ]
        }]},
      options: {
        legend: {
          display: true,
          position: 'right'
        }
      }
    });

    var request2 = new XMLHttpRequest();
    request2.open('GET', '/stats/users', true);

    request2.onload = function() {
      if (request2.status >= 200 && request2.status < 400) {
        var data = JSON.parse(request2.responseText);
        usersChart.config.data.datasets[0].data = [data.confirmed_count, data.unconfirmed_count];
        usersChart.update();
      } else {
        console.log('There was an issue on the server.');
      }
    };

    request2.onerror = function() {
      console.log('There was an issue with the request.');
    };

    request2.send();
  </script>
{% endblock %}

web/app/templates/main/event.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% from "macros.html" import form_field %}

{% block page_content %}
  <div class="row">
    <div class="col-md-12">
      <h1>Event #{{ event.id}}</h1>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <h3>Detaljer</h3>

      <p>
        Start: {{ event.start }}<br/>
        Slut: {{ event.end }}
      </p>
      <p>
        Anmälan börjar: {{ event.signup_start }}<br/>
        Anmälan slutar: {{ event.signup_end }}
      </p>
    </div>

    <div class="col-md-8">
      <h3>Deltagare</h3>
      <p>{{ event.attendees|length }} deltagare har anmält sig, totalt finns det {{ event.limit }} platser.</p>

      <table class="table table-striped">
        <thead>
          <th>Säljnummer</th>
          <th>E-mail</th>
          <th>Förnamn</th>
          <th>Efternamn</th>
          <th>Konto</th>
        </thead>
        <tbody>
          {% for attendance in event.attendees|sort(attribute='seller_id') %}
          <tr>
            <td>{{ attendance.seller_id }}</td>
            <td>{{ attendance.user.email }}</td>
            <td>{{ attendance.user.first_name if attendance.user.first_name }}</td>
            <td>{{ attendance.user.last_name if attendance.user.last_name }}</td>
            <td>{{ 'Ja' if attendance.user.account }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>

    </div>
  </div>
{% endblock %}

web/app/templates/main/event_with_bank_details.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% from "macros.html" import form_field %}

{% block page_content %}
  <div class="row">
    <div class="col-md-12">
      <h1>Event #{{ event.id}} - {{ event.start }}</h1>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <h3>Deltagare</h3>

      <table class="table table-striped">
        <thead>
          <th>Säljnummer</th>
          <th>Namn</th>
          <!--<th>E-mail</th>-->
          <th>Bank</th>
          <th>Clearing</th>
          <th>Kontonummer</th>
          <th>Utbetalt?</th>
        </thead>
        <tbody>
          {% for attendance in event.attendees|sort(attribute='seller_id') %}
          <tr>
            <td>{{ attendance.seller_id }}</td>
            <td>{{ attendance.user.last_name }}, {{ attendance.user.first_name }}</td>
            <!--<td>{{ attendance.user.email }}</td>-->
            {% if attendance.user.account %}
            <td>{{ attendance.user.account.bank }}</td>
            <td>{{ attendance.user.account.clearing }}</td>
            <td>{{ attendance.user.account._number }}</td>
            {% else %}
            <td>-</td>
            <td>-</td>
            <td>-</td>
            {% endif %}
            <td></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>

    </div>
  </div>
{% endblock %}

web/app/templates/main/gdpr.html
{% extends "base.html" %}

{% block page_content %}
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1>Personuppgiftshantering</h1>
      {% include 'gdpr.html' %}
    </div>
  </div>

{% endblock %}

web/app/templates/main/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
  <div class="row">
    <div id="front-page-header" class="col-md-12 text-center">
      <h1>Eksjö klädbytardag</h1>
      <img src="{{ url_for('static', filename='images/logo.png') }}" width="80%">
    </div>
  </div>

  <div class="row">

    <!-- Köp -->
    <div class="col-md-4">
      <h2>Var med och fynda</h2>
      <p>
        Kom till Klädbytardagen och fynda. Vi har öppet {{ moment(current_event.start).format('dddd [den] D MMMM [klockan] HH:mm') }} till {{ moment(current_event.end).format('HH:mm') }}.
        Barnkläder och skor säljs i Missionskyrkan på Österlånggatan 3 medan leksaker och tillbehör i säljs på Fröhuset på Österlånggatan 6.
        Utanför Missionskyrkan kan man köpa korv med bröd som säljs av Eksjö Missionskyrkas Equmeniascouter. Betalning med Swish eller kontanter.
      </p>

      <!-- Sälj -->
      <h2>Var med och sälj</h2>
      <p>
        Bli en av våra många säljare. Det är enkelt!
        För att kunna anmäla dig som säljare behöver du registrera en email-adress och ett lösenord.
        Från och med den {{ moment(current_event.signup_start).format('D MMMM [klockan] HH:mm') }} kan man anmäla sig här och bli en av våra 130 säljare.
      </p>
      <p>
        Efter du anmält dig får du ett email med ett unikt säljnummer.
        Du ska sedan märka de barnkläder och saker som du vill sälja enligt den instruktion som kommer i emailet.
        Det som ska säljas lämnas in fredagen innan Klädbytardagen mellan 15.00 och 18.00.
        Om du vill ha tillbaka osålda artiklar hämtas dessa på Klädbytardagen mellan 16.45 och 17.00.
        Du som säljare får 75 % i förtjänst av dina sålda varor.
        Resterande pengar går till Eksjö Missionkyrkas barn och ungdomsverksamhet, Fröhuset och välgörenhet.
      </p>
    </div>

    <!-- Dela -->
    <div class="col-md-4">
      <div class="row">
        <div class="col-md-12">
          <h2>Dela med världen</h2>
          <p>
            Ta del av mer information om vår klädbytardag och sprid den vidare så att fler får möjligheten att köpa och sälja!
          </p>
          <p>
            <a href="https://www.facebook.com/kladbytardagen/">Klädbytardagen på Facebook</a><br>
            <a href="http://www.missionskyrkaneksjo.se/missionskyrkaneksjo/extern/start.php">Eksjö Missionskyrka</a>
          </p>
        </div>
      </div>

      <!-- Volontär -->
      <div class="row">
        <div class="col-md-12">
          <h2>Var med som volontär</h2>
          <p>
            Vi är många som hjälps åt för att genomföra klädbytardagen.
            Klädytardagen skulle aldrig gå att genomföra utan ett stort antal människor som lägger ned tid och engagemang för att det ska bli av.
            Det krävs uppemot 100 personer för att klara av en bytardag!
            Om man vill vara med och förköpa under 2 timmar på fredagskvällen måste man fullgöra minst 3 arbetspass.
          </p>
          <p>
            <a href="{{ url_for('main.personal') }}">Information för personal</a>
          </p>
        </div>
      </div>

      <!-- Historia -->
      <div class="row">
        <div class="col-md-12">
          <h2>Hur det började</h2>
          <p>
            Eksjö Missionskyrkas barn- och ungdomsförening Equmenia Eksjö har sedan 2001 anordnat Klädbytardagen.
            Begagnade barnkläder, skor, leksaker och tillbehör får nya ägare.
            Ett stort antal frivilliga sorterar inlämnade saker och sköter försäljningen.
            Det som inte säljs eller hämtas efteråt skickas till Brobygget i Estland, ett samarbete mellan missionskyrkor på småländska höglandet och Unionskyrkan i Estland, och hamnar sedan i second hand-butiker i Estland.
          </p>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="row">
      </div>

      {% if attending %}
        <!-- User is already signed up to current event. -->
        <div class="col-md-12 well">
          <h3>Välkommen som säljare</h3>
          <p>Trevligt att just du vill vara med och sälja!</p>
        </div>
      {% else %}
        <!-- First box, registration. -->
        <div class="col-md-12 well arrow_box">
          <h3>Registrera dig</h3>
          {% if current_user.is_anonymous %}
            <p>Detta är första steget för att bli säljare. Vi kommer inte dela din adress med någon och bara skicka information om klädbytardagen.</p>
            <p class="text-center"><a href="{{ url_for('auth.register') }}" class="btn btn-lg btn-primary" role="button">Registrera mig</a></p>
            <hr/>
            <p>Har du redan registrerat dig kan du logga in här.</p>
            <p class="text-center"><a href="{{ url_for('auth.login') }}" class="btn btn-lg btn-primary" role="button">Logga in</a></p>
          {% else %}
            <p>Hej {{ current_user.first_name }}, tack för att du har registrerat dig.</p>
            <p>När anmälan är öppen har du möjlighet att anmäla dig med knappen i rutan nedan.</p>
          {% endif %}
        </div>

        <!-- Second box, signup. -->
        <div class="col-md-12 well arrow_box2">
          <h3>Anmäl dig</h3>
          {% if attending %}
            <p>Tack för att du anmält dig!</p>
            <div class="text-center">
              <button type="button" class="btn btn-lg btn-primary" disabled>Anmäl mig</button>
            </div>
          {% else %}
            {% if current_event.signup_over() %}
              <p>Alla platser är bokade och anmälan är över för den här gången.</p>
              <div class="text-center">
                <button type="button" class="btn btn-lg btn-primary" disabled>Anmäl mig</button>
              </div>
            {% else %}
              {% if current_event.signup_open() %}
                {% if current_user.is_anonymous %}
                  <p>Anmälan är öppen, men du är inte inloggad som en registrerad användare.</p>
                  <div class="text-center">
                    <button type="button" class="btn btn-lg btn-primary" disabled>Anmäl mig</button>
                  </div>
                {% else %}
                  <p>Anmälan är öppen, använd knappen nedan.</p>
                  <p class="text-warning">Tänk på att din plats är värdefull. Vi tar inte in reserver om du får förhinder, så anmäl dig bara om du är säker på att du kan delta.</p>
                  <form class="form form-horizontal" method="post" role="form">
                    {{ form.hidden_tag() }}
                    <div class="text-center">
                      {{ form.submit(class="btn btn-lg btn-primary") }}
                    </div>
                  </form>
                {% endif %}
              {% else %}
                <p>Anmälan har inte öppnat ännu.</p>
                <p>Anmälan öppnar {{ moment(current_event.signup_start).fromNow() }}.</p>
                <div class="text-center">
                  <button type="button" class="btn btn-lg btn-primary" disabled>Anmäl mig</button>
                </div>
              {% endif %}
            {% endif %}
          {% endif %}
        </div>
        {% endif %}
    </div>

  </div>
{% endblock %}

web/app/templates/main/list_events.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% from "macros.html" import form_field %}

{% block page_content %}
  <div class="row">
    <div class="col-md-12">
      <h1>Skapa nytt event</h1>

      <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}

        <div class="row">
          <div class="col-md-6">
            {{ form_field(form.start) }}
            {{ form_field(form.end) }}
            {{ form_field(form.limit) }}
          </div>
          <div class="col-md-6">
            {{ form_field(form.signup_start) }}
            {{ form_field(form.signup_end) }}
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            {{ form.submit(class="btn btn-default") }}
          </div>
        </div>
      </form>


      <h1>Alla event</h1>

      <table class="table table-striped">
        <thead>
          <th>Start</th>
          <th>Slut</th>
          <th>Anmälan börjar</th>
          <th>Anmälan slutar</th>
          <th>Max antal</th>
          <th></th>
        </thead>
        <tbody>
          {% for event in events %}
          <tr>
            <td>{{ event.start }}</td>
            <td>{{ event.end }}</td>
            <td>{{ event.signup_start }}</td>
            <td>{{ event.signup_end }}</td>
            <td>{{ event.limit }}</td>
            <td><a href="{{ url_for('main.event', id=event.id) }}">Detaljer</a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

{% endblock %}

web/app/templates/main/list_users.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% from "macros.html" import form_field %}

{% block page_content %}
  <div class="row">
    <div class="col-md-12">
{#      <h1>Skapa ny användare</h1>

      <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}

        <div class="row">
          <div class="col-md-6">
            {{ form_field(form.start) }}
            {{ form_field(form.end) }}
            {{ form_field(form.limit) }}
          </div>
          <div class="col-md-6">
            {{ form_field(form.signup_start) }}
            {{ form_field(form.signup_end) }}
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            {{ form.submit(class="btn btn-default") }}
          </div>
        </div>
      </form>
#}

      <h1>Alla användare</h1>

      <table class="table table-striped">
        <thead>
          <th>Epostadress</th>
          <th>Förnamn</th>
          <th>Efternamn</th>
          <th></th>
        </thead>
        <tbody>
          {% for user in users %}
          <tr>
            <td>{{ user.email }}</td>
            <td>{{ user.first_name }}</td>
            <td>{{ user.last_name }}</td>
            <td><a href="{{ url_for('main.user_profile', id=user.id) }}">Detaljer</a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

{% endblock %}

web/app/templates/main/profile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% from "macros.html" import form_field %}

{% block page_content %}
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1>Din profil</h1>
      <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}

        {{ form_field(form.email) }}
        {{ form_field(form.first_name) }}
        {{ form_field(form.last_name) }}
        {{ form_field(form.phone) }}

        <div class="panel panel-default">
          <div class="panel-heading">Bankkonto för utbetalningar</div>
          <div class="panel-body">
            {% if user.account %}
              <p>
                Bank: {{ user.account.bank }}</br>
                Konto: {{ user.account.clearing }} - {{ user.account.number }}
              </p>
              <a href="{{ url_for('main.profile_bank') }}">Ändra konto</a>
            {% else %}
              <p>Inget konto har angetts. <a href="{{ url_for('main.profile_bank') }}">Ange konto</a></p>
            {% endif %}
          </div>
        </div>

        {{ form.submit(class="btn btn-default") }}
      </form>
    </div>
  </div>

{% endblock %}

web/app/templates/main/profile_bank.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% from "macros.html" import form_field %}

{% block page_content %}
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1>Bankkonto för utbetalningar</h1>
      <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}

        {{ form_field(form.bank) }}
        {{ form_field(form.clearing) }}
        {{ form_field(form.number) }}

        {{ form.submit(class="btn btn-default") }}
    </div>
  </div>

{% endblock %}

web/app/templates/main/user_profile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1>Profil för {{ user.first_name }} {{ user.last_name }}</h1>
      <p>Användaren sågs senast för {{ moment(user.last_seen).fromNow() }} ({{ moment(user.last_seen).format('YYYY-MM-DD HH:mm:ss') }}).</p>
      <p>
        Epostadress {{ user.email }} {{ '<span style="color: red;"><i>ej</i> bekräftad</span>'|safe if not user.confirmed }}<br/>
        Telefonnummer: {{ user.phone if user.phone }}<br/>
        Förnamn: {{ user.first_name }}<br/>
        Efternamn: {{ user.last_name }}
      </p>

      {% if user.gdpr_consent %}
        <p>GDPR-policy accepterad.</p>
      {% else %}
        <p>GDPR-policy <span><i>inte</i></span> accepterad.</p>
      {% endif %}

      {% if user.account %}
        <p>Användaren har angett ett bankkonto.</p>
      {% endif %}
    </div>
  </div>

{% endblock %}